FROM node:alpine

ENV FRONT_URL=http://localhost:5000

WORKDIR /app

RUN apk add --no-cache curl git && \
    git clone https://github.com/tkasu/backend-example-docker.git . && \
    npm install && \
    apk del curl git && \
    adduser -D app_user && \
    chown -R app_user .

USER app_user

EXPOSE 8000

CMD npm start
